### PR TITLE
🔨 chore(format): format entire codebase

### PR DESCRIPTION
**Pull request by pauliesnug**
I GENUINELY HAVE NO IDEA HOW ONE CODEBASE CAN BE SO MESSY LMAO??

### CODE REVIEW

**Comment by RuinTD** [comment]
Apologies, but I have no intent to switch away from Prettier.

**Comment by pauliesnug** [comment]
> Apologies, but I have no intent to switch away from Prettier.

why though

**Comment by pauliesnug** [comment]
every other polyfrost typescript code uses standardized formatting

**Comment by pauliesnug** [comment]
why do we need this one repo to make my eyes bleed

**Comment by RuinTD** [comment]
Is Prettier not a standardized format? I use it for all my projects.
I'm fine with some linting for code quality (like to ensure `===`, which I don't normally use), but I'd still prefer Prettier for formatting, since it has always matched my code style.

EDIT: See here: https://prettier.io/docs/en/integrating-with-linters

**Comment by pauliesnug** [comment]
> Is Prettier not a standardized format? I use it for all my projects. I'm fine with some linting for code quality (like to ensure `===`, which I don't normally use), but I'd still prefer Prettier for formatting, since it has always matched my code style.

it is standardized. but personally, its super opinionated and messy for me. it's really bad for accessibility by default, and it doesnt factor in consistency, because prettier isnt AST based.

**Comment by pauliesnug** [comment]
and eslint + prettier is a whole mess in and of itself, whereas eslint can do everything prettier does and more

**Comment by KTibow** [comment]
This isn't Polyfrost so I see no need to apply its formatting.
Its formatting appears nonstandard anyway, and doesn't even configure the width of tabs.
Eslint only needs to do the job of linting. This config appears to be somewhat abandoned (dead website) and makes eslint run slower by assigning it more tasks.

**Comment by pauliesnug** [comment]
> This isn't Polyfrost so I see no need to apply its formatting. Its formatting appears nonstandard anyway, and doesn't even configure the width of tabs. Eslint only needs to do the job of linting. This config appears to be somewhat abandoned (dead website) and makes eslint run slower by assigning it more tasks.

iirc skyclient is part of polyfrost but idc. it's not non-standard, all tabs are 4 space and hard-tabs for accessibility. eslint does formatting too with its auto fixing feature. i also made the config and update it regularly, and its optimized to be used with the official eslint auto-fix feature

**Comment by pauliesnug** [comment]
i dont think the new eslint commit actually works, not 100% sure. also it doesnt really fix/help with anything

**Comment by RuinTD** [comment]
> i dont think the new eslint commit actually works, not 100% sure. also it doesnt really fix/help with anything

Everything that was reported by ESLint was fixed in the same commit. You may also need to turn on Use Flat Config in VS Code settings. I’ll add that to workspace settings.

**Comment by pauliesnug** [comment]
> > i dont think the new eslint commit actually works, not 100% sure. also it doesnt really fix/help with anything
> 
> Everything that was reported by ESLint was fixed in the same commit. You may also need to turn on Use Flat Config in VS Code settings. I’ll add that to workspace settings.

no i mean like. the way you set it up doesnt really warrant the use of eslint. i would just merge this commit but whatever

**Pull request closed without merging**
